package water;

import org.openjdk.jol.info.ClassLayout;
import org.openjdk.jol.vm.VM;

import static java.lang.System.out;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'michal' at '10/27/16 2:49 PM' with Gradle 3.1
 *
 * @author michal, @date 10/27/16 2:49 PM
 */
public class JolH2O {
    public static void main(String[] args) {
        out.println(VM.current().details());
        out.println(ClassLayout.parseClass(water.Key.class).toPrintable());
    }
}
